### ISSUE TITLE
Rangers - Switching between Archery and Dual Wield

### ISSUE THREAD

**Issue by zenevan** [Nyyrazzilyss/NyyLIB#120] opened 2018-01-22 05:46 UTC
Knockdown Shot button not disappearing
when switching between bow and dual wield.

Still sends KS instead of SS
Half of the archery code starts firing as well,

using powerful recurve bow for bow
and scepter / emerald longsword for weapons

**Comment by Nyyrazzilyss** [comment] 2018-01-22 13:59
This was hopefully fixed in the dev I posted a couple days ago - What version are you using? Type '@version'

**Comment by zenevan** [comment] 2018-01-22 14:41
Script version: 12/23/2017 NyyLIB011rc1b https://github.com/Nyyrazzilyss/NyyLIB

**Comment by Nyyrazzilyss** [comment] 2018-01-22 14:43
This would be a duplicate of https://github.com/Nyyrazzilyss/NyyLIB/issues/106

should be fixed in 1/20 dev

**Closed by Nyyrazzilyss** 2018-01-22 14:43 UTC
Labels: duplicate
